sudo: false
language: node_js
node_js:
  - "0.10.30"

branches:
  only:
    - master

addons:
  postgresql: "9.3"

before_install:
  # Position ourselves to start the test in "script" phase
  - cd ~/build/fronteerio/grasshopper

  # Configure postgres
  - psql -c 'create database grasshoppertest;' -U postgres
  - printf "\n\nconfig.db.username = 'postgres';" >> config.js

script:
  - grunt test-coverage-coveralls

after_failure:
  - cat tests.log | node_modules/.bin/bunyan -l debug

notifications:
  email:
    - simon@fronteer.io
    - nicolaas@fronteer.io
